services:
  - type: web
    name: portfolio
    env: node
    buildCommand: npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
    headers:
      - path: /*.js
        name: Content-Type
        value: application/javascript
      - path: /*.mjs
        name: Content-Type
        value: application/javascript
      - path: /*.css
        name: Content-Type
        value: text/css
      - path: /*.html
        name: Content-Type
        value: text/html
      - path: /*.json
        name: Content-Type
        value: application/json
      - path: /*.svg
        name: Content-Type
        value: image/svg+xml 