services:
  - type: web
    name: portfolio
    env: node
    buildCommand: npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
    headers:
      - path: /*.js
        name: Content-Type
        value: application/javascript; charset=utf-8
      - path: /*.mjs
        name: Content-Type
        value: application/javascript; charset=utf-8
      - path: /*.css
        name: Content-Type
        value: text/css; charset=utf-8
      - path: /*.html
        name: Content-Type
        value: text/html; charset=utf-8
      - path: /*.json
        name: Content-Type
        value: application/json; charset=utf-8
      - path: /*.svg
        name: Content-Type
        value: image/svg+xml; charset=utf-8
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /*
        name: Cache-Control
        value: no-cache 